import { Song, Album, Artist } from './types';

/** Set to true when lyrics content is ready to show in the player. */
export const LYRICS_ENABLED = false;

export const PUBLIC_AUDIO = {
  naatuNaatu: '/audio/naatu-naatu.mp3',
  aayaSher: '/audio/aaya-sher.mp3',
} as const;

export const TELUGU_ALBUMS: Album[] = [
  {
    id: 'album-1',
    title: 'RRR',
    artist: 'M. M. Keeravani',
    year: '2022',
    coverImage: '/covers/albumcovers/rrr-cover.jpg',
    genre: 'Epic Cinematic & Mass',
    accentColor: 'from-red-600 to-red-950/80',
  },
  {
    id: 'album-2',
    title: 'The Paradise',
    artist: 'Anirudh Ravichander',
    year: '2026',
    coverImage: '/covers/albumcovers/paradise-cover.jpg',
    genre: 'Mass Folk & Action',
    accentColor: 'from-orange-600 to-orange-950/80',
  },
  {
    id: 'album-3',
    title: 'Bruce Lee: The Fighter',
    artist: 'Thaman S',
    year: '2015',
    coverImage: '/covers/albumcovers/bruce-lee-cover.jpg',
    genre: 'Action/Comedy',
    accentColor: 'from-amber-600 to-amber-950/80',
  },
  {
    id: 'album-4',
    title: 'Committee Kurrollu',
    artist: 'Anudeep Dev',
    year: '2024',
    coverImage: '/covers/albumcovers/committee-kurrollu-cover.jpg',
    genre: 'Comedy-Drama',
    accentColor: 'from-teal-600 to-teal-950/80',
  },
  {
    id: 'album-5',
    title: 'Andala Rakshasi',
    artist: 'Radhan',
    year: '2012',
    coverImage: '/covers/albumcovers/andhala-rakshashi-cover.jpg',
    genre: 'Romance/Drama',
    accentColor: 'from-pink-600 to-pink-950/80',
  },
  {
    id: 'album-6',
    title: 'George Reddy',
    artist: 'Suresh Bobblli, Harshavardhan Rameshwar',
    year: '2019',
    coverImage: '/covers/albumcovers/george-reddy-cover.jpg',
    genre: 'Action/Drama',
    accentColor: 'from-rose-600 to-rose-950/80',
  },
  {
    id: 'album-7',
    title: 'Manchi Manasulu',
    artist: 'Ilaiyaraaja',
    year: '1992',
    coverImage: '/covers/albumcovers/manchi-manasulu-cover.jpg',
    genre: 'Family Drama',
    accentColor: 'from-indigo-600 to-indigo-950/80',
  },
  {
    id: 'album-8',
    title: 'Tulasi',
    artist: 'Devi Sri Prasad',
    year: '2007',
    coverImage: '/covers/albumcovers/tulasi-cover.jpg',
    genre: 'Action/Drama',
    accentColor: 'from-cyan-600 to-cyan-950/80',
  },
  {
    id: 'album-9',
    title: 'Life Is Beautiful',
    artist: 'Mickey J Meyer',
    year: '2012',
    coverImage: '/covers/albumcovers/life-is-beautiful-cover.jpg',
    genre: 'Drama/Melodrama',
    accentColor: 'from-violet-600 to-violet-950/80',
  },
  {
    id: 'album-10',
    title: 'Suzume',
    artist: 'Kazuma Jinnouchi',
    year: '2022',
    coverImage: '/covers/albumcovers/suzume-cover.jpg',
    genre: 'Adventure/Drama',
    accentColor: 'from-sky-600 to-sky-950/80',
  },
];

export const TELUGU_SONGS: Song[] = [
  {
    id: 'song-1',
    title: 'Naatu Naatu',
    artist: 'Rahul Sipligunj, Kaala Bhairava',
    album: 'RRR',
    duration: '3:36',
    durationInSeconds: 216,
    coverImage: '/covers/songcovers/naatu-naatu-song.jpg',
    genre: 'High Energy Dance',
    year: '2022',
    streamUrl: PUBLIC_AUDIO.naatuNaatu,
    audioUrl: PUBLIC_AUDIO.naatuNaatu,
    lyrics: 'Poleramma jathatlo... Naatu naatu...',
  },
  {
    id: 'song-2',
    title: 'Aaya Sher',
    artist: 'Anirudh Ravichander, Jangi Reddy, Arjun Chandy',
    album: 'The Paradise',
    duration: '4:48',
    durationInSeconds: 288,
    coverImage: '/covers/songcovers/aaya-sher-song.jpg',
    genre: 'Mass Folk Beat',
    year: '2026',
    streamUrl: PUBLIC_AUDIO.aayaSher,
    audioUrl: PUBLIC_AUDIO.aayaSher,
    lyrics: 'Pottu pottu aakalundhi aaya sher...',
  },
  {
    id: 'song-3',
    title: 'Le Chalo',
    artist: 'Thaman S, Megha',
    album: 'Bruce Lee: The Fighter',
    duration: '4:30',
    durationInSeconds: 270,
    coverImage: '/covers/songcovers/lay-chalo-song.jpg',
    genre: 'Tollywood / Indian Pop and Dance music',
    year: '2015',
    streamUrl: '/audio/lay-chalo.mpeg',
    audioUrl: '/audio/lay-chalo.mpeg',
  },
  {
    id: 'song-4',
    title: 'Aa Rojulu Malli Raavu',
    artist: 'Karthik',
    album: 'Committee Kurrollu',
    duration: '4:13',
    durationInSeconds: 253,
    coverImage: '/covers/songcovers/aa-rojulu-malli-raavu-song.jpg',
    genre: 'Melody, Feel Good, and Friendship',
    year: '2024',
    streamUrl: '/audio/aa-rojulu-malli-raavu.mpeg',
    audioUrl: '/audio/aa-rojulu-malli-raavu.mpeg',
  },
  {
    id: 'song-5',
    title: 'Manasu Palike',
    artist: 'Rakendu Mouli',
    album: 'Andala Rakshasi',
    duration: '3:48',
    durationInSeconds: 228,
    coverImage: '/covers/songcovers/manasu-palike-song.jpg',
    genre: 'Telugu romantic and melodic song',
    year: '2012',
    streamUrl: '/audio/manasu-palike.mpeg',
    audioUrl: '/audio/manasu-palike.mpeg',
  },
  {
    id: 'song-6',
    title: 'Bullet',
    artist: 'Mangli',
    album: 'George Reddy',
    duration: '3:26',
    durationInSeconds: 206,
    coverImage: '/covers/songcovers/bullet-song.jpg',
    genre: 'High-energy, folk-style track',
    year: '2019',
    streamUrl: '/audio/bullet.mpeg',
    audioUrl: '/audio/bullet.mpeg',
  },
  {
    id: 'song-7',
    title: 'Jabilli Kosam - Female',
    artist: 'S. Janaki',
    album: 'Manchi Manasulu',
    duration: '3:46',
    durationInSeconds: 226,
    coverImage: '/covers/songcovers/jabilli-kosam(female)-song.jpg',
    genre: 'Romantic, and Melody',
    year: '1992',
    streamUrl: '/audio/jabilli-kosam(female).mpeg',
    audioUrl: '/audio/jabilli-kosam(female).mpeg',
  },
  {
    id: 'song-8',
    title: 'Vennelintha',
    artist: 'Venu Srirangam, Sunitha',
    album: 'Tulasi',
    duration: '4:17',
    durationInSeconds: 257,
    coverImage: '/covers/songcovers/vennelintha-song.jpg',
    genre: 'Romantic Melody',
    year: '2007',
    streamUrl: '/audio/vennelintha.mpeg',
    audioUrl: '/audio/vennelintha.mpeg',
  },
  {
    id: 'song-9',
    title: 'Beautiful Girl',
    artist: 'Karthik',
    album: 'Life Is Beautiful',
    duration: '4:44',
    durationInSeconds: 284,
    coverImage: '/covers/songcovers/beautiful-girl-song.jpg',
    genre: 'Indian Pop and Contemporary Tollywood (Filmi)',
    year: '2012',
    streamUrl: '/audio/beautiful-girl.mpeg',
    audioUrl: '/audio/beautiful-girl.mpeg',
  },
  {
    id: 'song-10',
    title: 'suzume no tojimari',
    artist: 'RADWIMPS',
    album: 'Suzume',
    duration: '3:56',
    durationInSeconds: 236,
    coverImage: '/covers/songcovers/suzume-no-tojimari-song.jpg',
    genre: 'Adventure/Drama',
    year: '2022',
    streamUrl: '/audio/suzume.mpeg',
    audioUrl: '/audio/suzume.mpeg',
  },
];

export const STARTUP_SONG =
  TELUGU_SONGS.find((song) => song.title === 'Naatu Naatu') ?? TELUGU_SONGS[0];

export const getAlbumSongs = (albumTitle: string): Song[] =>
  TELUGU_SONGS.filter((song) => song.album === albumTitle);

export const songMatchesArtist = (song: Song, artistName: string): boolean =>
  song.artist.split(',').some((name) => name.trim() === artistName);

export const TELUGU_ARTISTS: Artist[] = [
  {
    id: 'artist-1',
    name: 'Rahul Sipligunj',
    role: 'Playback Singer',
    image: '/covers/songcovers/naatu-naatu-song.jpg',
    bio: 'Telugu playback singer known for high-energy folk and dance hits including the Oscar-winning Naatu Naatu.',
    monthlyListeners: '6.2M',
  },
  {
    id: 'artist-2',
    name: 'Anirudh Ravichander',
    role: 'Music Director / Playback Singer',
    image: '/covers/songcovers/aaya-sher-song.jpg',
    bio: 'One of South India\'s biggest music composers, delivering chart-topping mass beats and melodies across Tamil and Telugu cinema.',
    monthlyListeners: '18.6M',
  },
  {
    id: 'artist-3',
    name: 'Karthik',
    role: 'Playback Singer',
    image: '/covers/songcovers/aa-rojulu-malli-raavu-song.jpg',
    bio: 'Versatile Telugu playback singer celebrated for melodic, feel-good, and romantic film songs.',
    monthlyListeners: '4.8M',
  },
  {
    id: 'artist-4',
    name: 'Mangli',
    role: 'Playback Singer',
    image: '/covers/songcovers/bullet-song.jpg',
    bio: 'Popular folk and mass-style Telugu singer known for powerful, high-energy performances.',
    monthlyListeners: '3.5M',
  },
  {
    id: 'artist-5',
    name: 'S. Janaki',
    role: 'Playback Singer',
    image: '/covers/songcovers/jabilli-kosam(female)-song.jpg',
    bio: 'Legendary Indian playback singer with a timeless voice across Telugu, Tamil, and Kannada cinema.',
    monthlyListeners: '2.1M',
  },
  {
    id: 'artist-6',
    name: 'RADWIMPS',
    role: 'Japanese Rock Band',
    image: '/covers/songcovers/suzume-no-tojimari-song.jpg',
    bio: 'Japanese rock band known for cinematic soundtracks including Suzume and Your Name.',
    monthlyListeners: '12.4M',
  },
];
